import = [
  # theme
  "~/.config/alacritty/themes/themes/nord.toml"
]

[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },
]

[window]
opacity = 1
startup_mode = "Maximized"

[font]
size=14
