import = [
  # theme
  "~/.config/alacritty/themes/themes/nord.toml"
]

[keyboard]
bindings = [
  # cmd+enterでフルスクリーンモードに入る
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },
  # MacOSのバックスラッシュキー押下が¥キー入力判定されてしまうので、変換する
  { key = "¥", chars = "\\"},
]

[window]
opacity = 1
startup_mode = "Maximized"
decorations = "None"

[font]
size=14
